version: "3"

services:
  bot:
    build: .
    container_name: discord-bot
    environment:
      - TOKEN=${TOKEN}
      - GUILD=${GUILD}
      - PY_ENV=production

    command: "python -u /app/bot/bot.py"



